name: todo_list_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get:
  cupertino_icons:
  hive:
  hive_flutter:
  path_provider:
  flutter_local_notifications: 
  intl:
  flutter_slidable:
  timezone:
  omni_datetime_picker:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^3.0.0
  build_runner:
  hive_generator:

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo/to-do-list.png"
  min_sdk_android: 21
  remove_alpha_ios: true